### DISCUSSION TITLE
OpenTelemetry : Metrics

### DISCUSSION THREAD

**Discussion by adugar-conga** [open-telemetry/community#1016] [Community Discussions]
Friends,

**Ask** : We are working on setting up opentelemetry metrics, which will collect service defined custom metrics.

**Setup** : We have installed OTLP Agent which will collect all metrics, and traces, listening on 4317 port number using grpc protocol.

**Usage** : OTLP Agent should send the metrics to OTLP Exporter which is setup on a public endpoint. 

**Issue**: Based on the above Ask, Setup and Usage, we are not able to export the metrics, although the traces are getting exported.

**Question** : We havent setup Prometheus and only using OTLP exporter  to collect the metrics. Do we need Prometheus exporter along with OTLP exporter ?

If there is any other issue in my setup or usage, pls let me know

_Thanks in Advance
Anil Dugar_

**Comment by austinlparker** [comment]
Do you have a metrics export pipeline set up in your agent config? If you enable logging on your metrics pipeline, do you see metrics being created?

**Reply by adugar-conga** [reply]
Yes the metrics export pipeline is created in the agent config, but the question is does it need prometheus as part of export pipeline ?

**Reply by austinlparker** [reply]
No, prometheus isn't needed to export metrics via OTLP. I'd add some loggers to your agent and make sure the metrics are actually getting exported, and seeing if you can do the same on the receiving side.

**Reply by adugar-conga** [reply]
what are some loggers to be added in the agent to make sure the metrics are getting exported ?

**Reply by adugar-conga** [reply]
Here is my otel-config, Can you help ?

fullnameOverride: otel
image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.40.0
command:
  name: otelcontribcol
securityContext:
  runAsUser: 0
extraEnvs:
  - name: KUBE_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: KUBE_NODE_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: MY_POD_IP
    valueFrom:
        fieldRef:
            fieldPath: status.podIP
clusterRole:
  create: true
  name: otel
  rules: 
    - apiGroups: [""]
      resources:
      - nodes
      - nodes/stats
      - services
      - endpoints
      - pods
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources:
      - configmaps
      verbs: ["get"]
    - nonResourceURLs: ["/metrics", "/metrics-text"]
      verbs: ["get"]
agentCollector:
  containerLogs:
    enabled: true
  configOverride:
    exporters:      
      otlp:
        endpoint: my-public-otlp-endpoint
      logging: {}        
    processors:
      memory_limiter:
        limit_percentage: 80
        spike_limit_percentage:  25
        check_interval: 5s
      batch:
        timeout: 10s
      resource/prometheus:
        attributes:
          - key: host.name
            action: delete
          - key: job
            action: delete
          - key: instance
            action: delete
          - key: port
            action: delete
          - key: scheme
            action: delete
      resource/kubeletstats:
        attributes:
          - key: service.name
            from_attribute: k8s.container.name
            action: upsert
      resource:
        attributes:
          - key: k8s.cluster.name
            value: docker-desktop
            action: insert
          - key: k8s.namespace.name
            value: default
            #pattern: ^(?P<deployment_context>.*).*-(?P<deployment_env>.*).*$
            action: insert
          - key: deployment.environment
            #from_attribute: k8s.namespace.name 
            value: "adugar-local-dev-env-dep3"
            action: insert
          - key: service.namespace
            value: default
            action: insert
          - key: service.instance.id
            from_attribute: k8s.pod.name
            action: insert
          - key: service.name
            from_attribute: k8s.container.name
            action: upsert
          - key: service.name
            from_attribute: k8s.pod.labels.app
            action: upsert
      k8sattributes:
        filter:
          node_from_env_var: KUBE_NODE_NAME
        extract:
          metadata:
            - k8s.pod.name
            - k8s.node.name
            - k8s.namespace.name
            - k8s.deployment.name
            - k8s.pod.start_time
          labels:
            - key: app
            - key: release
      k8sattributes/pod_uid:
        filter:
          node_from_env_var: KUBE_NODE_NAME
        extract:
          metadata:
            - k8s.pod.name
            - k8s.node.name
            - k8s.namespace.name
            - k8s.deployment.name
            - k8s.pod.start_time
          labels:
            - key: app
            - key: release
        pod_association:
          - from: resource_attribute
            name: k8s.pod.uid
    receivers:
      filelog:
        exclude:
          - /var/log/pods/kube-system_otel-agent-*/*/*.log
          - /var/log/pods/kube-system_datadog-*/*/*.log
        include:
          - /var/log/pods/*/*/*.log
        include_file_name: false
        include_file_path: true
        start_at: end
        operators:
          - type: router
            id: get-format
            routes:
              - output: parser-docker
                expr: '$$body matches "^\\{"'
              - output: parser-crio
                expr: '$$body matches "^[^ Z]+ "'
              - output: parser-containerd
                expr: '$$body matches "^[^ Z]+Z"'
          - type: regex_parser
            id: parser-crio
            regex: '^(?P<time>[^ Z]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) (?P<log>.*)$'
            output: extract_metadata_from_filepath
            timestamp:
              parse_from: time
              layout_type: gotime
              layout: '2006-01-02T15:04:05.000000000-07:00'
          - type: regex_parser
            id: parser-containerd
            regex: '^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) (?P<log>.*)$'
            output: extract_metadata_from_filepath
            timestamp:
              parse_from: time
              layout: '%Y-%m-%dT%H:%M:%S.%LZ'
          - type: json_parser
            id: parser-docker
            output: extract_metadata_from_filepath
            timestamp:
              parse_from: time
              layout: '%Y-%m-%dT%H:%M:%S.%LZ'
          - type: regex_parser
            id: extract_metadata_from_filepath
            regex: '^.*\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[a-f0-9\-]{32,36})\/(?P<container_name>[^\._]+)\/(?P<run_id>\d+)\.log$'
            parse_from: '$$attributes["file.path"]'
          - type: metadata
            resource:
              k8s.container.name: EXPR($.container_name)
              k8s.namespace.name: EXPR($.namespace)
              k8s.pod.name: EXPR($.pod_name)
              k8s.pod.uid: EXPR($.uid)
          - type: restructure
            id: clean-up-log-body
            ops:
              - move:
                  from: log
                  to: $
        prometheus:
            config:
                scrape_configs:
                    - job_name: opentelemetry-collector
                scrape_interval: 10s
                - job_name: scrape_applications
                scrape_interval: 15s
                scrape_timeout: 10s
                metrics_path: /metrics
                scheme: http
                follow_redirects: true
                kubernetes_sd_configs:
                - role: pod
                follow_redirects: true
                namespaces:
                own_namespace: true
                relabel_configs:
                - source_labels: [__meta_kubernetes_pod_labelpresent_scrape_metrics,__meta_kubernetes_pod_container_port_number]
                separator: ;
                regex: true;4317
                action: keep
            # - job_name: apps
              # scrape_interval: 10s
              # kubernetes_sd_configs:
                # - role: pod
                  # selectors:
                    # - role: pod
                      # field: spec.nodeName=$KUBE_NODE_NAME
              # relabel_configs:
                  # - source_labels: [__meta_kubernetes_pod_ready]
                    # action: keep
                    # regex: "true"
                  # - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]       
                    # action: keep
                    # regex: "true"
                  # - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                    # action: replace
                    # target_label: __metrics_path__
                    # regex: (.+)
                  # - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                    # action: replace
                    # target_label: __address__
                    # regex: (.+)(?::\d+);(\d+)
                    # replacement: $$1:$$2
      kubeletstats:
        collection_interval: 10s
        auth_type: serviceAccount
        endpoint: '${KUBE_NODE_IP}:10250'
        insecure_skip_verify: true
        metric_groups:
          - node
          - container
      otlp:
        protocols:          
          grpc:
    service:
      pipelines:
        metrics:
          exporters: [otlp, logging]
          processors: [memory_limiter, k8sattributes, resource]
          receivers: [otlp]
        metrics/kubelet:
           exporters:  [otlp, logging]
           processors: [memory_limiter, k8sattributes/pod_uid, batch, resource, resource/kubeletstats]
           receivers:  [kubeletstats, otlp]
        traces:
          exporters: [otlp, logging]
          processors: [memory_limiter, k8sattributes, batch, resource]
          receivers: [otlp]
        logs:
          exporters: [otlp, logging]
          processors: [memory_limiter, k8sattributes/pod_uid, batch, resource]
          receivers: [filelog]

**Reply by austinlparker** [reply]
You can add a debug logger to your export pipelines (as seen [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/examples/local/otel-config.yaml)) to ensure that metrics are making it out through the exporter. You can also increase the log verbosity of the collector by changing it's log verbosity (as seen [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md#version-036-and-above)).

It's also very difficult to read your config, could you remove the extraneous details and format it in a code block?

**Reply by anildugar** [reply]
I have simplified the config
**IMPORTANT: We are using below image
**### Here is the error we are getting while deploying the collector : "error": "rpc error: code = DeadlineExceeded desc = context deadline exceeded"**
   repository: otel/opentelemetry-collector-contrib
   tag: "0.47.0"
  helm chart version : 0.12.1**

**Here is the simplified config**

# Config
```
fullnameOverride: otel3
image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.47.0"
command:
  name: otelcol-contrib

serviceAccount:
   create: true
   annotations: {}
   name: ""

ports:
  metrics:
      enabled: true
    containerPort: 8888
    servicePort: 8888
    protocol: TCP

agentCollector:
  enabled: true
  
  containerLogs:
    enabled: true
  configOverride:
    receivers:
      filelog:
          exclude:
            - /var/log/pods/*/opentelemetry-collector/*.log
            - /var/log/pods/kube*/*/*.log
          include:
            - /var/log/pods/*/*/*.log
          start_at: end
      otlp:
        protocols:
          grpc:
    
    exporters:
      otlp:
        endpoint: signals-grpc.prod-sodium.conga-panoptos.com:443
      # log to the console
      logging:
        loglevel: debug
     
    processors:      
      batch:
      resource:
        attributes:
          - key: k8s.cluster.name
            value: docker-desktop
            action: insert
          - key: k8s.namespace.name
            value: default
            #pattern: ^(?P<deployment_context>.*).*-(?P<deployment_env>.*).*$
            action: insert
          - key: deployment.environment
            #from_attribute: k8s.namespace.name 
            value: "adugar-local-dev-env-dep5"
            action: insert
          - key: service.namespace
            value: default
            action: insert
          - key: service.instance.id
            from_attribute: k8s.pod.name
            action: insert
          - key: service.name
            from_attribute: k8s.container.name
            action: upsert
          - key: service.name
            from_attribute: k8s.pod.labels.app
            action: upsert
   
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [logging, otlp]
        metrics:
          receivers: [otlp] 
          processors: [batch, resource]
          exporters: [otlp]  `

```
