### DISCUSSION TITLE
AWS Auth in otel-collector awsemfexporter for EKS

### DISCUSSION THREAD

**Discussion by ssmith-boomfantasy** [open-telemetry/community#1051] [Community Discussions]
I'm trying to figure out an acceptable way to get AWS auth (ACCESS_KEY_ID and SECRET) into a place where the collector can use them to push to Cloud Watch.  I know that I can set them as environment variables but I'm curious if I can use credentials that I already have stored in a k8s Secret.  

The exporter docs point at the aws-go docs for the auth chain.  I know the options.  Just not how to make the key available.  https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awsemfexporter

I'm using a very simple configuration
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-collector
spec:
  mode: deployment
  config: |
    receivers:
    
      prometheus:
        config:
          scrape_configs:
            - job_name: kubernetes-apiservers
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              kubernetes_sd_configs:
              - role: endpoints
              relabel_configs:
              - action: keep
                regex: default;kubernetes;https
                source_labels:
                - __meta_kubernetes_namespace
                - __meta_kubernetes_service_name
                - __meta_kubernetes_endpoint_port_name
              scheme: https
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: true

    processors:
      batch:
        timeout: 30s
        send_batch_size: 10000
    
    exporters:
      logging:
        loglevel: debug

      awsemf:
        region: us-east-1
    
    service:
      pipelines:
        metrics:
          receivers:
            - prometheus
          processors: 
            - batch
          exporters:
            - awsemf
            - logging
  ```
I'm getting a very clear error stating that I don't have the credentials.
`2022-05-02T19:34:22.355Z	warn	cwlogs@v0.45.1/pusher.go:280	Failed to create stream token	{"kind": "exporter", "name": "awsemf", "error": "NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"}`

Is there a way to set environment variables from a Secret similar to how the Deployment works?   Is there some documentation that I haven't found that shows how to do this?

Thanks for any help.
