### DISCUSSION TITLE
Exporting every single data point using file exporter

### DISCUSSION THREAD

**Discussion by zmitchell** [open-telemetry/community#1067] [Community Discussions]
Hi, I already have an application configured to collect metrics with [opentelemetry-rust](https://github.com/open-telemetry/opentelemetry-rust) and send them another service for observability. However, I would like to run some tests locally for debugging purposes.

I'm processing frames of a video, so I'd like to export metrics for every frame (time to process, etc). I see that I can use the file exporter to save metrics locally, so I've tried doing that. This is my config:
```
receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  file:
    path: ./otel_metrics.json

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
```

I have the exporter period set to 5s elsewhere in my code. When I run my application with say 90 frames at 30fps (3s runtime, shorter than the 5s exporter period) the `otel_metrics.json` file contains a single JSON object and is missing many of the metrics. When I run my application for longer (300 frames at 30fps, 10s runtime) I get a second JSON object in `otel_metrics.json` that contains the missing metrics, but only a single datapoint for each one. In either case I would expect to see `N` datapoints where `N` is the number of frames I've processed.

It seems like there's sampling or filtering going on, but I don't know enough about OpenTelemetry to know whether I've misconfigured my collector in such a way.

For reference, one of the metrics I'm interested in is a `f64_value_recorder`.

**Comment by codeboten** [comment]
Is it possible the batch processor is causing the confusion here? If you remove it from the metrics pipeline, you should be able to see the datapoint individually.

**Comment by zmitchell** [comment]
I edited my collector config to look like this:

```
receivers:
  otlp:
    protocols:
      grpc:

processors:

exporters:
  file:
    path: ./otel_metrics.json

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [file]
```

I still only see a single datapoint when I expect to see something like 100 data points.
