### DISCUSSION TITLE
Traces not getting sent by Collector

### DISCUSSION THREAD

**Discussion by sarasensible** [open-telemetry/community#1513] [Community Discussions]
I am running Tempo 2.1.1 with Open Telemetry collector 0.76.1 in a sidecar configuration in Kubernetes.  I have two services, one of which is successfully sending traces to Tempo which are visible in Grafana, the other is not.  The one that is not is a Python auto-instrumented deployment.  I _think_ it is sending traces via grpc but I am not 100% sure.  However I have tried both configurations with grpc and http and neither work.  I have tried sending just a bare http sample trace to tempo on the http 4318 port and it works fine.  My colleague who developed the Python code has also confirmed that the docker image itself can send traces in a local environment.  All this leads me to conclude something is up with either the instrumentation or the opentelemetrycollector.

Instrumentation:
```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  annotations:
    instrumentation.opentelemetry.io/default-auto-instrumentation-dotnet-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:0.7.0
    instrumentation.opentelemetry.io/default-auto-instrumentation-java-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.11.1
    instrumentation.opentelemetry.io/default-auto-instrumentation-nodejs-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.11.1
    instrumentation.opentelemetry.io/default-auto-instrumentation-python-image: ""
spec:
  env:
  - name: OTEL_EXPORTER_OTLP_TIMEOUT
    value: "20"
  - name: SPLUNK_TRACE_RESPONSE_HEADER_ENABLED
    value: "true"
  exporter:
    endpoint: http://localhost:4317
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.11.1
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.11.1
  propagators:
  - tracecontext
  - baggage
  - b3
  python:
    env:
    - name: OTEL_LOG_LEVEL
      value: debug
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://localhost:4317
    - name: OTEL_EXPORTER_OTLP_INSECURE
      value: "true"
    - name: OTEL_SERVICE_NAME
      value: weather-sensible-engine-service
    - name: OTEL_TRACES_SAMPLER
      value: parentbased_always_on
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.36b0
  resource: {}
  sampler: {}
```

OpenTelemetryCollector
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
spec:
  config: |
    receivers:
        otlp:
            protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
    exporters:
        logging:
            loglevel: debug
        otlp:
          endpoint: tempo-tempo-distributed-distributor.monitoring.svc.cluster.local:4317
          tls:
            insecure: true
    service:
        telemetry:
            logs:
                level: debug
        pipelines:
            metrics:
               receivers: [otlp]
               exporters: [logging]
            traces:
                receivers: [otlp]
                exporters: [logging, otlp]
                processors: []
  mode: sidecar
  resources: {}
  targetAllocator: {}
  upgradeStrategy: automatic
status:
  version: 0.76.1
```

Deployment annotations:
```
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: weather-sensible-engine-telemetry-instrumentation
        sidecar.opentelemetry.io/inject: weather-sensible-engine-telemetry-collector
```

Tracing code:
```
# configure global Tracing directives
def configure_global_provider(
    service_name,
    exporter: Optional[SpanExporter] = None,
    processor: Optional[SpanProcessor] = None,
):
    """
    This can only be called this way once per process since provider can only be set
    once
    """
    global _CONFIGURED

    if not _CONFIGURED:
        provider = TracerProvider(
            resource=Resource.create({"service.name": service_name})
        )

        if not exporter:
            exporter = ConsoleSpanExporter()

        if not processor:
            processor = BatchSpanProcessor(exporter)

        provider.add_span_processor(processor)
        trace.set_tracer_provider(provider)
        _CONFIGURED = True
    return None


def configure_provider_from_envvar():
    # Configure the tracer to export traces to Jaeger
    service_name = (os.environ.get("OTEL_SERVICE_NAME", "unknown"),)

    # sampler is already configurable by envvar per sdk see:
    # https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-sdk/src/opentelemetry/sdk/trace/sampling.py

    # only supports otlp exporter.
    exporter = OTLPSpanExporter(
        endpoint=os.environ.get("OTEL_EXPORTER_OTLP_ENDPOINT", "otel-collector:4317"),
        insecure=os.environ.get("OTEL_EXPORTER_OTLP_INSECURE", True),
    )

    processor = BatchSpanProcessor(exporter)
    return configure_global_provider(service_name, exporter, processor)


@dataclass
class SensibleTracer:
    name: str
    _tracer: Optional[Tracer] = None

    def __post_init__(self):
        # This is a noop if its already run
        configure_global_provider(self.name)

        if self._tracer is None:
            self._tracer = trace.get_tracer(self.name)

    def trace(self) -> Callable[[GenericFunc], GenericFunc]:
        def wrapper(func: GenericFunc) -> GenericFunc:
            span_name = f"{self.name}-{func.__name__}"
            if inspect.iscoroutinefunction(func):

                @wraps(func)
                async def inner(*args, **kwargs) -> Any:
                    with self._tracer.start_as_current_span(span_name):
                        # add other baggage/attrs here
                        return await func(*args, **kwargs)

            else:

                @wraps(func)
                def inner(*args, **kwargs) -> Any:
                    with self._tracer.start_as_current_span(span_name):
                        # add other baggage/attrs here
                        return func(*args, **kwargs)

            return inner

        return wrapper

    def instrument_module(self, module):
        for name in dir(module):
            obj = getattr(module, name)
            if isinstance(obj, FunctionType):
                setattr(module, name, self.trace()(obj))

    def __getattr__(self, attr):
        """pass off all other method and attribute requests to wrapped _tracer obj"""
        return getattr(self._tracer, attr)
```

The only logs in the opentelemetry manager look like this:
```
{"level":"info","ts":1685122180.37148,"logger":"instrumentation-resource","msg":"validate update","name":"weather-sensible-engine-telemetry-instrumentation"}
```

Any help would be greatly appreciated.
